# Generated by Django 5.1.6 on 2025-08-13 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0002_alter_cat_options_alter_healthnotes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6)),
                ('treatment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='cat.cat')),
            ],
        ),
    ]
