# Generated by Django 5.1.6 on 2025-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('Health issue', 'Health issue'), ('Neuter', 'Neuter'), ('Chip', 'Chip')], max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
    ]
