# Generated by Django 5.1.6 on 2025-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma_points',
            field=models.IntegerField(default=0),
        ),
    ]
