# Generated by Django 5.1.6 on 2025-08-12 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=7)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(38)])),
                ('photo', models.URLField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_fed', models.DateTimeField(blank=True, null=True)),
                ('last_water', models.DateTimeField(blank=True, null=True)),
                ('neutered', models.BooleanField(default=False)),
                ('chipped', models.BooleanField(default=False)),
                ('health_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='district.district')),
                ('color', models.ManyToManyField(related_name='cats', to='cat.color')),
            ],
        ),
        migrations.CreateModel(
            name='HealthNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(max_length=500)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='cat.cat')),
            ],
        ),
    ]
