# Generated by Django 5.1.6 on 2025-07-23 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0002_remove_district_cat_population_district_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=7)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(38)])),
                ('photo', models.URLField(blank=True, null=True)),
                ('locations_seen', models.CharField(max_length=100, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('neutered', models.BooleanField(default=False)),
                ('chipped', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='district.district')),
                ('color', models.ManyToManyField(related_name='cats', to='cat.color')),
            ],
        ),
    ]
