# Generated by Django 5.1.6 on 2025-08-11 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='last_fed',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cat',
            name='last_water',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='HealthNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(max_length=500)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='cat.cat')),
            ],
        ),
    ]
