# Generated by Django 5.1.6 on 2025-08-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'permissions': [('approve_cat', 'Can approve a cat')]},
        ),
        migrations.AlterModelOptions(
            name='healthnotes',
            options={'permissions': [('set_treatment_cost', 'Can set treatment cost')]},
        ),
    ]
