# Generated by Django 5.1.6 on 2025-08-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_cat_last_fed_cat_last_water_healthnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='last_fed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='last_water',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
