# Generated by Django 5.1.6 on 2025-08-14 00:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_alter_cat_options_alter_healthnotes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
