# Generated by Django 5.1.6 on 2025-08-11 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0001_initial'),
        ('district', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=7)),
                ('gave_food', models.BooleanField(default=False)),
                ('gave_water', models.BooleanField(default=False)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('time_met', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_sighting', to='cat.cat')),
                ('color', models.ManyToManyField(related_name='cat_sighting', to='cat.color')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_sighting', to='district.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_sighting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
