# Generated by Django 5.1.6 on 2025-07-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='cat_population',
        ),
        migrations.AddField(
            model_name='district',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
